### ISSUE TITLE
Failure to install art.msix at Step 4

### ISSUE THREAD

**Issue by IAmNadaman** [Kudayasu/Artifice#1]
App version: 1.1.0

Xbox OS Version: 10.0.25398.1762
Console: Xbox Series X and Xbox One "Durango"

![image](https://github.com/Kudayasu/Artifice/assets/13267910/69a3a6ac-3504-44e9-91f4-1c4e2760cb2a)

Clearing dev mode apps and factory ressetting the console seemed to make no difference.

**Comment by Kudayasu** [comment]
As mentioned previously, initial guess is XboxWDPDriver. When you get to this step, can you verify in Task Manager or any similar program, that it's properly being ran? It runs with a hidden window, but you should see XboxWDPDriver.exe active as the install takes place.

**Comment by IAmNadaman** [comment]
When I get to this step, I don't see this executable pop up in Task Manager.

**Comment by Kudayasu** [comment]
Was able to reproduce your output by renaming the exe. My question then, if you're sure nothing was renamed, is if you're using a third-party AV program, it might've flagged it. Otherwise, you can try extracting the program again from the zip. Could also verify that you can manually run the executable by CDing to your extracted directory, i.e. **C:\Users\\{YourUsername}\Desktop\publish\Scratch\WDP\XboxWDPDriver.exe** and invoking the exe directly, i.e. **XboxWdpDriver.exe /X:XBOXONE**

**Comment by IAmNadaman** [comment]
Wow, just putting the `publish` folder on my desktop worked! Previously I put the app in a secondary folder on one of my hard drives. It has now successfully been ran.

This was also a fresh installaton of Windows 11; no third party AV has been installed.

**Comment by Kudayasu** [comment]
Thank you for reporting an issue I had yet to encounter throughout my testing. 
Glad you got it working.
