### ISSUE TITLE
Either something changed or patched in the August 2024 build?

### ISSUE THREAD

**Issue by SternXD** [Kudayasu/Artifice#7]
Hello, I was just checking the latest build to see if it was patched and on `Version 10.0.26100.1836` aka August 2024 build it is now stuck at `Telnet session created` I will mention the admin account made on 4910 still works.

![image](https://github.com/user-attachments/assets/dd6162d5-c34f-442a-891b-33268f7ae748)

**Comment by Helloyunho** [comment]
Can confirm it doesn't work and instead gets stuck at the same step

**Comment by SternXD** [comment]
I think it might have something to do with a updated Telnetd executable?

**Comment by Kudayasu** [comment]
Telnet remains unchanged as far as I can tell, they just updated XboxDevService to call **GetImpersonationTokenFromProcess** for the **RecursiveCopy** function. You can take a better look at it in [MicrosoftAccountTokenProvider.dll](https://winbindex.m417z.com/?file=microsoftaccounttokenprovider.dll) with symbols. Otherwise, if you have physical access to your drive, you can try backing up the **user-devkit** xvd.

If not, take a look at the following [repo](https://github.com/PN-Tester/AppxPotato)
